[sources.syslog_in]
type = "syslog"
mode = "udp"
address = "0.0.0.0:514"

[transforms.shape_logs]
type = "remap"
inputs = ["syslog_in"]
source = '''
  . = .
'''

[sinks.microsoc_out]
type = "http"
inputs = ["shape_logs"]
uri = "http://127.0.0.1:5001/api/ingest"
encoding.codec = "json"
auth.strategy = "bearer"
auth.token = "YOUR_SECRET_MICRO_SOC_KEY"
