import base64, mimetypes, os, sqlite3
from datetime import datetime, timedelta
from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML

BASE_DIR = "/opt/micro-dfir"
DB_PATH = os.path.join(BASE_DIR, "siem.db")
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")
REPORT_OUTPUT_DIR = os.path.join(BASE_DIR, "reports")
os.makedirs(REPORT_OUTPUT_DIR, exist_ok=True)

# Kept in sync with app.py's COMPLIANCE_FRAMEWORKS -- both need the same key set, and
# this is also the one place the human-readable label lives (previously duplicated a
# second time in dashboard.html's JS as its own separate list).
COMPLIANCE_FRAMEWORK_LABELS = {
    'pci_dss': 'PCI DSS', 'hipaa': 'HIPAA', 'nist_800_53': 'NIST 800-53',
    'nist_csf': 'NIST CSF', 'iso_27001': 'ISO 27001', 'soc2': 'SOC 2',
    'cis_controls': 'CIS Controls', 'gdpr': 'GDPR',
}

# Action categories a compliance reviewer would specifically want called out, not
# buried in a full activity list -- user management, credential/cert changes, and
# anything that alters what gets retained.
AUDIT_SENSITIVE_ACTIONS = (
    'user_create', 'user_password_reset', 'user_delete',
    'soc_token_change', 'network_config_change', 'tls_cert_upload',
    'retention_policy_change', 'manual_log_purge', 'db_vacuum',
)
AUDIT_REPORT_ROW_CAP = 200

# Mirrors app.py's REPORT_BRANDING_DEFAULTS/REPORT_BRANDING_DIR exactly -- this script
# has no Flask app context (cron invokes it directly), so it can't import app.py's
# copy and keeps its own, same reasoning as RISK_SCORE_DEFAULTS/DB_PATH being
# duplicated across this codebase's standalone scripts rather than cross-imported.
REPORT_BRANDING_DIR = "/opt/micro-dfir/data/branding"
REPORT_BRANDING_DEFAULTS = {
    "company_name": "Micro DFIR", "logo_filename": None,
    "footer_text": "Generated by Micro DFIR SOAR Engine", "accent_color": "#0d6efd",
}

def _branding_context(conn):
    import json
    cfg = dict(REPORT_BRANDING_DEFAULTS)
    row = conn.execute("SELECT value FROM settings WHERE key = 'report_branding_config'").fetchone()
    if row and row[0]:
        try:
            cfg.update(json.loads(row[0]))
        except (ValueError, TypeError):
            pass
    cfg['logo_data_uri'] = None
    if cfg.get('logo_filename'):
        path = os.path.join(REPORT_BRANDING_DIR, cfg['logo_filename'])
        if os.path.exists(path):
            mime = mimetypes.guess_type(path)[0] or 'image/png'
            with open(path, 'rb') as f:
                cfg['logo_data_uri'] = f"data:{mime};base64,{base64.b64encode(f.read()).decode()}"
    return cfg

def _report_filename(label):
    # Was month-only ({label}_{YYYY_MM}.pdf) -- a second generation of the same report
    # type in the same month silently overwrote the first with no warning. Full
    # timestamp makes every generation its own file, which is what makes a real
    # history table (one row per file) meaningful instead of misleading.
    return f"{label}_Report_{datetime.now().strftime('%Y_%m_%d_%H%M%S')}.pdf"

def _render_and_write(template_name, context, output_name):
    html_out = Environment(loader=FileSystemLoader(TEMPLATE_DIR)).get_template(template_name).render(context)
    HTML(string=html_out).write_pdf(os.path.join(REPORT_OUTPUT_DIR, output_name))
    return output_name

def generate_security_report():
    conn = sqlite3.connect(DB_PATH); cursor = conn.cursor()
    thirty_days_ago = (datetime.utcnow() - timedelta(days=30)).isoformat()
    total_events = cursor.execute("SELECT COUNT(*) FROM events WHERE timestamp >= ?", (thirty_days_ago,)).fetchone()[0]
    total_alerts = cursor.execute("SELECT COUNT(*) FROM alerts WHERE timestamp >= ?", (thirty_days_ago,)).fetchone()[0]
    top_alerts = [{"title": r[0], "severity": r[1], "count": r[2]} for r in cursor.execute(
        "SELECT sr.title, a.severity, COUNT(a.id) as hit_count FROM alerts a JOIN sigma_rules sr ON a.rule_id = sr.id "
        "WHERE a.timestamp >= ? GROUP BY sr.title, a.severity ORDER BY hit_count DESC LIMIT 5", (thirty_days_ago,)
    ).fetchall()]

    context = {
        "date_generated": datetime.now().strftime("%B %d, %Y"),
        "report_title": "Managed Security Report",
        "branding": _branding_context(conn),
        "total_events": f"{total_events:,}", "total_alerts": f"{total_alerts:,}",
        "top_alerts": top_alerts,
    }
    conn.close()
    return _render_and_write('report_template.html', context, _report_filename('Security'))

def generate_compliance_report():
    conn = sqlite3.connect(DB_PATH); conn.row_factory = sqlite3.Row; cursor = conn.cursor()
    rows = cursor.execute(
        "SELECT compliance_tags, enabled FROM sigma_rules WHERE compliance_tags IS NOT NULL AND compliance_tags != ''"
    ).fetchall()

    coverage = {key: {'key': key, 'label': label, 'total': 0, 'enabled': 0} for key, label in COMPLIANCE_FRAMEWORK_LABELS.items()}
    for row in rows:
        # A rule can be tagged for more than one framework -- it counts toward each.
        for tag in (row['compliance_tags'] or '').split(','):
            if tag in coverage:
                coverage[tag]['total'] += 1
                if row['enabled']:
                    coverage[tag]['enabled'] += 1

    frameworks = sorted(coverage.values(), key=lambda f: f['label'])
    full_coverage_count = sum(1 for f in frameworks if f['total'] > 0 and f['enabled'] == f['total'])

    context = {
        "date_generated": datetime.now().strftime("%B %d, %Y"),
        "report_title": "Compliance Report",
        "branding": _branding_context(conn),
        "frameworks": frameworks,
        "full_coverage_count": full_coverage_count,
        "total_frameworks": len(frameworks),
    }
    conn.close()
    return _render_and_write('report_template_compliance.html', context, _report_filename('Compliance'))

def generate_audit_report():
    conn = sqlite3.connect(DB_PATH); conn.row_factory = sqlite3.Row; cursor = conn.cursor()
    thirty_days_ago = (datetime.now() - timedelta(days=30)).strftime('%Y-%m-%d %H:%M:%S')

    action_counts = [dict(r) for r in cursor.execute(
        "SELECT action, COUNT(*) as count FROM audit_log WHERE timestamp >= ? GROUP BY action ORDER BY count DESC",
        (thirty_days_ago,)
    ).fetchall()]

    placeholders = ','.join('?' for _ in AUDIT_SENSITIVE_ACTIONS)
    sensitive_events = [dict(r) for r in cursor.execute(
        f"SELECT timestamp, username, action, target_type, target_id, details FROM audit_log "
        f"WHERE timestamp >= ? AND action IN ({placeholders}) ORDER BY id DESC",
        (thirty_days_ago, *AUDIT_SENSITIVE_ACTIONS)
    ).fetchall()]

    total_events_count = cursor.execute("SELECT COUNT(*) FROM audit_log WHERE timestamp >= ?", (thirty_days_ago,)).fetchone()[0]
    recent_events = [dict(r) for r in cursor.execute(
        "SELECT timestamp, username, action, target_type, target_id FROM audit_log WHERE timestamp >= ? ORDER BY id DESC LIMIT ?",
        (thirty_days_ago, AUDIT_REPORT_ROW_CAP)
    ).fetchall()]

    context = {
        "date_generated": datetime.now().strftime("%B %d, %Y"),
        "report_title": "Audit Trail Report",
        "report_subtitle": "Last 30 days",
        "branding": _branding_context(conn),
        "action_counts": action_counts,
        "sensitive_events": sensitive_events,
        "recent_events": recent_events,
        "total_events_count": total_events_count,
        "truncated": total_events_count > AUDIT_REPORT_ROW_CAP,
        "row_cap": AUDIT_REPORT_ROW_CAP,
    }
    conn.close()
    return _render_and_write('report_template_audit.html', context, _report_filename('Audit'))

REPORT_GENERATORS = {
    'security': generate_security_report,
    'compliance': generate_compliance_report,
    'audit': generate_audit_report,
}

def _record_history(conn, report_type, filename, status, started_at, completed_at,
                     triggered_by, trigger_source, error_message=None):
    file_size = None
    if status == 'success' and filename:
        try:
            file_size = os.path.getsize(os.path.join(REPORT_OUTPUT_DIR, filename))
        except OSError:
            pass
    conn.execute(
        "INSERT INTO report_history (report_type, filename, status, triggered_by, trigger_source, "
        "started_at, completed_at, file_size_bytes, error_message) VALUES (?,?,?,?,?,?,?,?,?)",
        (report_type, filename, status, triggered_by, trigger_source, started_at, completed_at, file_size, error_message)
    )
    conn.commit()

# Single chokepoint for both triggering paths: cron calls this script directly with no
# Flask context (trigger_source='scheduled', triggered_by=None), the Reports tab's
# /reports/generate route shells out to it the same way with --user/--source=manual.
# History recording lives here (not in app.py) so both paths get a row without either
# duplicating the insert or a cron run silently having no record at all.
def run_report(report_type, triggered_by=None, trigger_source='manual'):
    started_at = datetime.now().isoformat()
    conn = sqlite3.connect(DB_PATH, timeout=30)
    try:
        # Defensive create -- mirrors _get_or_create_secret_key()'s own pattern in
        # app.py, in case this runs before migrate_report_history() has (e.g. cron
        # fires between a code deploy and the next app restart that runs migrations).
        conn.execute('''CREATE TABLE IF NOT EXISTS report_history (
            id INTEGER PRIMARY KEY AUTOINCREMENT, report_type TEXT NOT NULL, filename TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'success', triggered_by TEXT, trigger_source TEXT NOT NULL DEFAULT 'manual',
            started_at DATETIME, completed_at DATETIME, file_size_bytes INTEGER, error_message TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )''')
        filename = REPORT_GENERATORS.get(report_type, generate_security_report)()
        _record_history(conn, report_type, filename, 'success', started_at,
                         datetime.now().isoformat(), triggered_by, trigger_source)
    except Exception as e:
        _record_history(conn, report_type, '', 'failed', started_at,
                         datetime.now().isoformat(), triggered_by, trigger_source, str(e))
        conn.close()
        raise
    conn.close()

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('report_type', nargs='?', default='security')
    parser.add_argument('--user', default=None)
    parser.add_argument('--source', default='scheduled', choices=('manual', 'scheduled'))
    args = parser.parse_args()
    run_report(args.report_type, triggered_by=args.user, trigger_source=args.source)
