"""MITRE ATT&CK Enterprise reference data.

Sigma rule YAML tags encode ATT&CK info as free-text strings like
`attack.execution` (tactic name) and `attack.t1059`/`attack.t1059.001`
(technique/sub-technique ID) -- there is no structured field anywhere in a
rule. This module provides a static technique-ID -> (name, tactic) lookup so
that tag can be turned into something a coverage report can group and count.

TECHNIQUES covers the full MITRE ATT&CK Enterprise matrix (all active,
non-revoked/non-deprecated techniques and sub-techniques as of the source
snapshot below) -- generated once from the official MITRE CTI STIX bundle
(github.com/mitre-attack/attack-stix-data, enterprise-attack/enterprise-attack.json),
not a live sync (same "confirmed once, committed as a fixed list" pattern as
src/warninglists.py). A handful of techniques carry a legacy/non-standard
STIX kill-chain-phase name ('defense-impairment', 'stealth') instead of one
of the real 14 tactics -- both were verified against the public matrix and
mapped to 'defense-evasion' (e.g. T1218.011 Rundll32) so no active technique
is silently dropped. Re-generate by re-running the fetch + transform this was
built with if the matrix needs refreshing; a technique ID seen in a rule but
somehow still missing from TECHNIQUES still surfaces (see techniques_for_tags
below) -- just without a friendly name, grouped under the "Unmapped"
pseudo-tactic -- so a stale table degrades gracefully instead of hiding
coverage.
"""
import re

# The 14 MITRE ATT&CK Enterprise tactics, in their canonical kill-chain order.
TACTICS = [
    'reconnaissance', 'resource-development', 'initial-access', 'execution',
    'persistence', 'privilege-escalation', 'defense-evasion', 'credential-access',
    'discovery', 'lateral-movement', 'collection', 'command-and-control',
    'exfiltration', 'impact',
]

TACTIC_LABELS = {
    'reconnaissance': 'Reconnaissance',
    'resource-development': 'Resource Development',
    'initial-access': 'Initial Access',
    'execution': 'Execution',
    'persistence': 'Persistence',
    'privilege-escalation': 'Privilege Escalation',
    'defense-evasion': 'Defense Evasion',
    'credential-access': 'Credential Access',
    'discovery': 'Discovery',
    'lateral-movement': 'Lateral Movement',
    'collection': 'Collection',
    'command-and-control': 'Command and Control',
    'exfiltration': 'Exfiltration',
    'impact': 'Impact',
    'unmapped': 'Unmapped',
}

# technique_id -> (name, tactic). IDs are lowercase, no leading "t" -- e.g. the
# key for T1059.001 is '1059.001'. A handful of technique IDs collide across
# tactics in ATT&CK itself (e.g. T1078 "Valid Accounts" spans Initial Access,
# Persistence, Privilege Escalation, and Defense Evasion) -- disambiguated
# with a throwaway single-letter suffix purely as a dict key ('1078b', '1078c',
# ...); _display_id strips it back to the real ID. Sub-techniques fall back to
# their parent's tactic when the parent is listed but the sub-technique isn't
# (see lookup()).
TECHNIQUES = {
    '1001': ('Data Obfuscation', 'command-and-control'),
    '1001.001': ('Junk Data', 'command-and-control'),
    '1001.002': ('Steganography', 'command-and-control'),
    '1001.003': ('Protocol or Service Impersonation', 'command-and-control'),
    '1003': ('OS Credential Dumping', 'credential-access'),
    '1003.001': ('LSASS Memory', 'credential-access'),
    '1003.002': ('Security Account Manager', 'credential-access'),
    '1003.003': ('NTDS', 'credential-access'),
    '1003.004': ('LSA Secrets', 'credential-access'),
    '1003.005': ('Cached Domain Credentials', 'credential-access'),
    '1003.006': ('DCSync', 'credential-access'),
    '1003.007': ('Proc Filesystem', 'credential-access'),
    '1003.008': ('/etc/passwd and /etc/shadow', 'credential-access'),
    '1005': ('Data from Local System', 'collection'),
    '1006': ('Direct Volume Access', 'defense-evasion'),
    '1007': ('System Service Discovery', 'discovery'),
    '1008': ('Fallback Channels', 'command-and-control'),
    '1010': ('Application Window Discovery', 'discovery'),
    '1011': ('Exfiltration Over Other Network Medium', 'exfiltration'),
    '1011.001': ('Exfiltration Over Bluetooth', 'exfiltration'),
    '1012': ('Query Registry', 'discovery'),
    '1014': ('Rootkit', 'defense-evasion'),
    '1016': ('System Network Configuration Discovery', 'discovery'),
    '1016.001': ('Internet Connection Discovery', 'discovery'),
    '1016.002': ('Wi-Fi Discovery', 'discovery'),
    '1018': ('Remote System Discovery', 'discovery'),
    '1020': ('Automated Exfiltration', 'exfiltration'),
    '1020.001': ('Traffic Duplication', 'exfiltration'),
    '1021': ('Remote Services', 'lateral-movement'),
    '1021.001': ('Remote Desktop Protocol', 'lateral-movement'),
    '1021.002': ('SMB/Windows Admin Shares', 'lateral-movement'),
    '1021.003': ('Distributed Component Object Model', 'lateral-movement'),
    '1021.004': ('SSH', 'lateral-movement'),
    '1021.005': ('VNC', 'lateral-movement'),
    '1021.006': ('Windows Remote Management', 'lateral-movement'),
    '1021.007': ('Cloud Services', 'lateral-movement'),
    '1021.008': ('Direct Cloud VM Connections', 'lateral-movement'),
    '1025': ('Data from Removable Media', 'collection'),
    '1027': ('Obfuscated Files or Information', 'defense-evasion'),
    '1027.001': ('Binary Padding', 'defense-evasion'),
    '1027.002': ('Software Packing', 'defense-evasion'),
    '1027.003': ('Steganography', 'defense-evasion'),
    '1027.004': ('Compile After Delivery', 'defense-evasion'),
    '1027.005': ('Indicator Removal from Tools', 'defense-evasion'),
    '1027.006': ('HTML Smuggling', 'defense-evasion'),
    '1027.007': ('Dynamic API Resolution', 'defense-evasion'),
    '1027.008': ('Stripped Payloads', 'defense-evasion'),
    '1027.009': ('Embedded Payloads', 'defense-evasion'),
    '1027.010': ('Command Obfuscation', 'defense-evasion'),
    '1027.011': ('Fileless Storage', 'defense-evasion'),
    '1027.012': ('LNK Icon Smuggling', 'defense-evasion'),
    '1027.013': ('Encrypted/Encoded File', 'defense-evasion'),
    '1027.014': ('Polymorphic Code', 'defense-evasion'),
    '1027.015': ('Compression', 'defense-evasion'),
    '1027.016': ('Junk Code Insertion', 'defense-evasion'),
    '1027.017': ('SVG Smuggling', 'defense-evasion'),
    '1027.018': ('Invisible Unicode', 'defense-evasion'),
    '1029': ('Scheduled Transfer', 'exfiltration'),
    '1030': ('Data Transfer Size Limits', 'exfiltration'),
    '1033': ('System Owner/User Discovery', 'discovery'),
    '1036': ('Masquerading', 'defense-evasion'),
    '1036.001': ('Invalid Code Signature', 'defense-evasion'),
    '1036.002': ('Right-to-Left Override', 'defense-evasion'),
    '1036.003': ('Rename Legitimate Utilities', 'defense-evasion'),
    '1036.004': ('Masquerade Task or Service', 'defense-evasion'),
    '1036.005': ('Match Legitimate Resource Name or Location', 'defense-evasion'),
    '1036.006': ('Space after Filename', 'defense-evasion'),
    '1036.007': ('Double File Extension', 'defense-evasion'),
    '1036.008': ('Masquerade File Type', 'defense-evasion'),
    '1036.009': ('Break Process Trees', 'defense-evasion'),
    '1036.010': ('Masquerade Account Name', 'defense-evasion'),
    '1036.011': ('Overwrite Process Arguments', 'defense-evasion'),
    '1036.012': ('Browser Fingerprint', 'defense-evasion'),
    '1037': ('Boot or Logon Initialization Scripts', 'persistence'),
    '1037b': ('Boot or Logon Initialization Scripts', 'privilege-escalation'),
    '1037.001': ('Logon Script (Windows)', 'persistence'),
    '1037.001b': ('Logon Script (Windows)', 'privilege-escalation'),
    '1037.002': ('Login Hook', 'persistence'),
    '1037.002b': ('Login Hook', 'privilege-escalation'),
    '1037.003': ('Network Logon Script', 'persistence'),
    '1037.003b': ('Network Logon Script', 'privilege-escalation'),
    '1037.004': ('RC Scripts', 'persistence'),
    '1037.004b': ('RC Scripts', 'privilege-escalation'),
    '1037.005': ('Startup Items', 'persistence'),
    '1037.005b': ('Startup Items', 'privilege-escalation'),
    '1039': ('Data from Network Shared Drive', 'collection'),
    '1040': ('Network Sniffing', 'credential-access'),
    '1040b': ('Network Sniffing', 'discovery'),
    '1041': ('Exfiltration Over C2 Channel', 'exfiltration'),
    '1046': ('Network Service Discovery', 'discovery'),
    '1047': ('Windows Management Instrumentation', 'execution'),
    '1048': ('Exfiltration Over Alternative Protocol', 'exfiltration'),
    '1048.001': ('Exfiltration Over Symmetric Encrypted Non-C2 Protocol', 'exfiltration'),
    '1048.002': ('Exfiltration Over Asymmetric Encrypted Non-C2 Protocol', 'exfiltration'),
    '1048.003': ('Exfiltration Over Unencrypted Non-C2 Protocol', 'exfiltration'),
    '1049': ('System Network Connections Discovery', 'discovery'),
    '1052': ('Exfiltration Over Physical Medium', 'exfiltration'),
    '1052.001': ('Exfiltration over USB', 'exfiltration'),
    '1053': ('Scheduled Task/Job', 'execution'),
    '1053b': ('Scheduled Task/Job', 'persistence'),
    '1053c': ('Scheduled Task/Job', 'privilege-escalation'),
    '1053.002': ('At', 'execution'),
    '1053.002b': ('At', 'persistence'),
    '1053.002c': ('At', 'privilege-escalation'),
    '1053.003': ('Cron', 'execution'),
    '1053.003b': ('Cron', 'persistence'),
    '1053.003c': ('Cron', 'privilege-escalation'),
    '1053.005': ('Scheduled Task', 'execution'),
    '1053.005b': ('Scheduled Task', 'persistence'),
    '1053.005c': ('Scheduled Task', 'privilege-escalation'),
    '1053.006': ('Systemd Timers', 'execution'),
    '1053.006b': ('Systemd Timers', 'persistence'),
    '1053.006c': ('Systemd Timers', 'privilege-escalation'),
    '1053.007': ('Container Orchestration Job', 'execution'),
    '1053.007b': ('Container Orchestration Job', 'persistence'),
    '1053.007c': ('Container Orchestration Job', 'privilege-escalation'),
    '1055': ('Process Injection', 'privilege-escalation'),
    '1055b': ('Process Injection', 'defense-evasion'),
    '1055.001': ('Dynamic-link Library Injection', 'privilege-escalation'),
    '1055.001b': ('Dynamic-link Library Injection', 'defense-evasion'),
    '1055.002': ('Portable Executable Injection', 'privilege-escalation'),
    '1055.002b': ('Portable Executable Injection', 'defense-evasion'),
    '1055.003': ('Thread Execution Hijacking', 'privilege-escalation'),
    '1055.003b': ('Thread Execution Hijacking', 'defense-evasion'),
    '1055.004': ('Asynchronous Procedure Call', 'privilege-escalation'),
    '1055.004b': ('Asynchronous Procedure Call', 'defense-evasion'),
    '1055.005': ('Thread Local Storage', 'privilege-escalation'),
    '1055.005b': ('Thread Local Storage', 'defense-evasion'),
    '1055.008': ('Ptrace System Calls', 'privilege-escalation'),
    '1055.008b': ('Ptrace System Calls', 'defense-evasion'),
    '1055.009': ('Proc Memory', 'privilege-escalation'),
    '1055.009b': ('Proc Memory', 'defense-evasion'),
    '1055.011': ('Extra Window Memory Injection', 'privilege-escalation'),
    '1055.011b': ('Extra Window Memory Injection', 'defense-evasion'),
    '1055.012': ('Process Hollowing', 'privilege-escalation'),
    '1055.012b': ('Process Hollowing', 'defense-evasion'),
    '1055.013': ('Process Doppelgänging', 'privilege-escalation'),
    '1055.013b': ('Process Doppelgänging', 'defense-evasion'),
    '1055.014': ('VDSO Hijacking', 'privilege-escalation'),
    '1055.014b': ('VDSO Hijacking', 'defense-evasion'),
    '1055.015': ('ListPlanting', 'privilege-escalation'),
    '1055.015b': ('ListPlanting', 'defense-evasion'),
    '1056': ('Input Capture', 'credential-access'),
    '1056b': ('Input Capture', 'collection'),
    '1056.001': ('Keylogging', 'credential-access'),
    '1056.001b': ('Keylogging', 'collection'),
    '1056.002': ('GUI Input Capture', 'credential-access'),
    '1056.002b': ('GUI Input Capture', 'collection'),
    '1056.003': ('Web Portal Capture', 'credential-access'),
    '1056.003b': ('Web Portal Capture', 'collection'),
    '1056.004': ('Credential API Hooking', 'credential-access'),
    '1056.004b': ('Credential API Hooking', 'collection'),
    '1057': ('Process Discovery', 'discovery'),
    '1059': ('Command and Scripting Interpreter', 'execution'),
    '1059.001': ('PowerShell', 'execution'),
    '1059.002': ('AppleScript', 'execution'),
    '1059.003': ('Windows Command Shell', 'execution'),
    '1059.004': ('Unix Shell', 'execution'),
    '1059.005': ('Visual Basic', 'execution'),
    '1059.006': ('Python', 'execution'),
    '1059.007': ('JavaScript', 'execution'),
    '1059.008': ('Network Device CLI', 'execution'),
    '1059.009': ('Cloud API', 'execution'),
    '1059.010': ('AutoHotKey & AutoIT', 'execution'),
    '1059.011': ('Lua', 'execution'),
    '1059.012': ('Hypervisor CLI', 'execution'),
    '1059.013': ('Container CLI/API', 'execution'),
    '1068': ('Exploitation for Privilege Escalation', 'privilege-escalation'),
    '1069': ('Permission Groups Discovery', 'discovery'),
    '1069.001': ('Local Groups', 'discovery'),
    '1069.002': ('Domain Groups', 'discovery'),
    '1069.003': ('Cloud Groups', 'discovery'),
    '1070': ('Indicator Removal', 'defense-evasion'),
    '1070.003': ('Clear Command History', 'defense-evasion'),
    '1070.004': ('File Deletion', 'defense-evasion'),
    '1070.005': ('Network Share Connection Removal', 'defense-evasion'),
    '1070.006': ('Timestomp', 'defense-evasion'),
    '1070.007': ('Clear Network Connection History and Configurations', 'defense-evasion'),
    '1070.008': ('Clear Mailbox Data', 'defense-evasion'),
    '1070.009': ('Clear Persistence', 'defense-evasion'),
    '1070.010': ('Relocate Malware', 'defense-evasion'),
    '1071': ('Application Layer Protocol', 'command-and-control'),
    '1071.001': ('Web Protocols', 'command-and-control'),
    '1071.002': ('File Transfer Protocols', 'command-and-control'),
    '1071.003': ('Mail Protocols', 'command-and-control'),
    '1071.004': ('DNS', 'command-and-control'),
    '1071.005': ('Publish/Subscribe Protocols', 'command-and-control'),
    '1072': ('Software Deployment Tools', 'execution'),
    '1072b': ('Software Deployment Tools', 'lateral-movement'),
    '1074': ('Data Staged', 'collection'),
    '1074.001': ('Local Data Staging', 'collection'),
    '1074.002': ('Remote Data Staging', 'collection'),
    '1078': ('Valid Accounts', 'initial-access'),
    '1078b': ('Valid Accounts', 'persistence'),
    '1078c': ('Valid Accounts', 'privilege-escalation'),
    '1078d': ('Valid Accounts', 'defense-evasion'),
    '1078.001': ('Default Accounts', 'initial-access'),
    '1078.001b': ('Default Accounts', 'persistence'),
    '1078.001c': ('Default Accounts', 'privilege-escalation'),
    '1078.001d': ('Default Accounts', 'defense-evasion'),
    '1078.002': ('Domain Accounts', 'initial-access'),
    '1078.002b': ('Domain Accounts', 'persistence'),
    '1078.002c': ('Domain Accounts', 'privilege-escalation'),
    '1078.002d': ('Domain Accounts', 'defense-evasion'),
    '1078.003': ('Local Accounts', 'initial-access'),
    '1078.003b': ('Local Accounts', 'persistence'),
    '1078.003c': ('Local Accounts', 'privilege-escalation'),
    '1078.003d': ('Local Accounts', 'defense-evasion'),
    '1078.004': ('Cloud Accounts', 'initial-access'),
    '1078.004b': ('Cloud Accounts', 'persistence'),
    '1078.004c': ('Cloud Accounts', 'privilege-escalation'),
    '1078.004d': ('Cloud Accounts', 'defense-evasion'),
    '1080': ('Taint Shared Content', 'lateral-movement'),
    '1082': ('System Information Discovery', 'discovery'),
    '1083': ('File and Directory Discovery', 'discovery'),
    '1087': ('Account Discovery', 'discovery'),
    '1087.001': ('Local Account', 'discovery'),
    '1087.002': ('Domain Account', 'discovery'),
    '1087.003': ('Email Account', 'discovery'),
    '1087.004': ('Cloud Account', 'discovery'),
    '1090': ('Proxy', 'command-and-control'),
    '1090.001': ('Internal Proxy', 'command-and-control'),
    '1090.002': ('External Proxy', 'command-and-control'),
    '1090.003': ('Multi-hop Proxy', 'command-and-control'),
    '1090.004': ('Domain Fronting', 'command-and-control'),
    '1091': ('Replication Through Removable Media', 'initial-access'),
    '1091b': ('Replication Through Removable Media', 'lateral-movement'),
    '1092': ('Communication Through Removable Media', 'command-and-control'),
    '1095': ('Non-Application Layer Protocol', 'command-and-control'),
    '1098': ('Account Manipulation', 'persistence'),
    '1098b': ('Account Manipulation', 'privilege-escalation'),
    '1098.001': ('Additional Cloud Credentials', 'persistence'),
    '1098.001b': ('Additional Cloud Credentials', 'privilege-escalation'),
    '1098.002': ('Additional Email Delegate Permissions', 'persistence'),
    '1098.002b': ('Additional Email Delegate Permissions', 'privilege-escalation'),
    '1098.003': ('Additional Cloud Roles', 'persistence'),
    '1098.003b': ('Additional Cloud Roles', 'privilege-escalation'),
    '1098.004': ('SSH Authorized Keys', 'persistence'),
    '1098.004b': ('SSH Authorized Keys', 'privilege-escalation'),
    '1098.005': ('Device Registration', 'persistence'),
    '1098.005b': ('Device Registration', 'privilege-escalation'),
    '1098.006': ('Additional Container Cluster Roles', 'persistence'),
    '1098.006b': ('Additional Container Cluster Roles', 'privilege-escalation'),
    '1098.007': ('Additional Local or Domain Groups', 'persistence'),
    '1098.007b': ('Additional Local or Domain Groups', 'privilege-escalation'),
    '1102': ('Web Service', 'command-and-control'),
    '1102.001': ('Dead Drop Resolver', 'command-and-control'),
    '1102.002': ('Bidirectional Communication', 'command-and-control'),
    '1102.003': ('One-Way Communication', 'command-and-control'),
    '1104': ('Multi-Stage Channels', 'command-and-control'),
    '1105': ('Ingress Tool Transfer', 'command-and-control'),
    '1106': ('Native API', 'execution'),
    '1110': ('Brute Force', 'credential-access'),
    '1110.001': ('Password Guessing', 'credential-access'),
    '1110.002': ('Password Cracking', 'credential-access'),
    '1110.003': ('Password Spraying', 'credential-access'),
    '1110.004': ('Credential Stuffing', 'credential-access'),
    '1111': ('Multi-Factor Authentication Interception', 'credential-access'),
    '1112': ('Modify Registry', 'persistence'),
    '1112b': ('Modify Registry', 'defense-evasion'),
    '1113': ('Screen Capture', 'collection'),
    '1114': ('Email Collection', 'collection'),
    '1114.001': ('Local Email Collection', 'collection'),
    '1114.002': ('Remote Email Collection', 'collection'),
    '1114.003': ('Email Forwarding Rule', 'collection'),
    '1115': ('Clipboard Data', 'collection'),
    '1119': ('Automated Collection', 'collection'),
    '1120': ('Peripheral Device Discovery', 'discovery'),
    '1123': ('Audio Capture', 'collection'),
    '1124': ('System Time Discovery', 'discovery'),
    '1125': ('Video Capture', 'collection'),
    '1127': ('Trusted Developer Utilities Proxy Execution', 'execution'),
    '1127b': ('Trusted Developer Utilities Proxy Execution', 'defense-evasion'),
    '1127.001': ('MSBuild', 'execution'),
    '1127.001b': ('MSBuild', 'defense-evasion'),
    '1127.002': ('ClickOnce', 'execution'),
    '1127.002b': ('ClickOnce', 'defense-evasion'),
    '1127.003': ('JamPlus', 'execution'),
    '1127.003b': ('JamPlus', 'defense-evasion'),
    '1129': ('Shared Modules', 'execution'),
    '1132': ('Data Encoding', 'command-and-control'),
    '1132.001': ('Standard Encoding', 'command-and-control'),
    '1132.002': ('Non-Standard Encoding', 'command-and-control'),
    '1133': ('External Remote Services', 'initial-access'),
    '1133b': ('External Remote Services', 'persistence'),
    '1134': ('Access Token Manipulation', 'privilege-escalation'),
    '1134b': ('Access Token Manipulation', 'defense-evasion'),
    '1134.001': ('Token Impersonation/Theft', 'privilege-escalation'),
    '1134.001b': ('Token Impersonation/Theft', 'defense-evasion'),
    '1134.002': ('Create Process with Token', 'privilege-escalation'),
    '1134.002b': ('Create Process with Token', 'defense-evasion'),
    '1134.003': ('Make and Impersonate Token', 'privilege-escalation'),
    '1134.003b': ('Make and Impersonate Token', 'defense-evasion'),
    '1134.004': ('Parent PID Spoofing', 'privilege-escalation'),
    '1134.004b': ('Parent PID Spoofing', 'defense-evasion'),
    '1134.005': ('SID-History Injection', 'privilege-escalation'),
    '1134.005b': ('SID-History Injection', 'defense-evasion'),
    '1135': ('Network Share Discovery', 'discovery'),
    '1136': ('Create Account', 'persistence'),
    '1136.001': ('Local Account', 'persistence'),
    '1136.002': ('Domain Account', 'persistence'),
    '1136.003': ('Cloud Account', 'persistence'),
    '1137': ('Office Application Startup', 'persistence'),
    '1137.001': ('Office Template Macros', 'persistence'),
    '1137.002': ('Office Test', 'persistence'),
    '1137.003': ('Outlook Forms', 'persistence'),
    '1137.004': ('Outlook Home Page', 'persistence'),
    '1137.005': ('Outlook Rules', 'persistence'),
    '1137.006': ('Add-ins', 'persistence'),
    '1140': ('Deobfuscate/Decode Files or Information', 'defense-evasion'),
    '1176': ('Software Extensions', 'persistence'),
    '1176.001': ('Browser Extensions', 'persistence'),
    '1176.002': ('IDE Extensions', 'persistence'),
    '1185': ('Browser Session Hijacking', 'collection'),
    '1187': ('Forced Authentication', 'credential-access'),
    '1189': ('Drive-by Compromise', 'initial-access'),
    '1190': ('Exploit Public-Facing Application', 'initial-access'),
    '1195': ('Supply Chain Compromise', 'initial-access'),
    '1195.001': ('Compromise Software Dependencies and Development Tools', 'initial-access'),
    '1195.002': ('Compromise Software Supply Chain', 'initial-access'),
    '1195.003': ('Compromise Hardware Supply Chain', 'initial-access'),
    '1197': ('BITS Jobs', 'execution'),
    '1197b': ('BITS Jobs', 'persistence'),
    '1197c': ('BITS Jobs', 'defense-evasion'),
    '1199': ('Trusted Relationship', 'initial-access'),
    '1200': ('Hardware Additions', 'initial-access'),
    '1201': ('Password Policy Discovery', 'discovery'),
    '1202': ('Indirect Command Execution', 'defense-evasion'),
    '1203': ('Exploitation for Client Execution', 'execution'),
    '1204': ('User Execution', 'execution'),
    '1204.001': ('Malicious Link', 'execution'),
    '1204.002': ('Malicious File', 'execution'),
    '1204.003': ('Malicious Image', 'execution'),
    '1204.004': ('Malicious Copy and Paste', 'execution'),
    '1204.005': ('Malicious Library', 'execution'),
    '1205': ('Traffic Signaling', 'persistence'),
    '1205b': ('Traffic Signaling', 'defense-evasion'),
    '1205c': ('Traffic Signaling', 'command-and-control'),
    '1205.001': ('Port Knocking', 'persistence'),
    '1205.001b': ('Port Knocking', 'defense-evasion'),
    '1205.001c': ('Port Knocking', 'command-and-control'),
    '1205.002': ('Socket Filters', 'persistence'),
    '1205.002b': ('Socket Filters', 'defense-evasion'),
    '1205.002c': ('Socket Filters', 'command-and-control'),
    '1207': ('Rogue Domain Controller', 'defense-evasion'),
    '1210': ('Exploitation of Remote Services', 'lateral-movement'),
    '1211': ('Exploitation for Stealth', 'defense-evasion'),
    '1212': ('Exploitation for Credential Access', 'credential-access'),
    '1213': ('Data from Information Repositories', 'collection'),
    '1213.001': ('Confluence', 'collection'),
    '1213.002': ('Sharepoint', 'collection'),
    '1213.003': ('Code Repositories', 'collection'),
    '1213.004': ('Customer Relationship Management Software', 'collection'),
    '1213.005': ('Messaging Applications', 'collection'),
    '1213.006': ('Databases', 'collection'),
    '1216': ('System Script Proxy Execution', 'defense-evasion'),
    '1216.001': ('PubPrn', 'defense-evasion'),
    '1216.002': ('SyncAppvPublishingServer', 'defense-evasion'),
    '1217': ('Browser Information Discovery', 'discovery'),
    '1218': ('System Binary Proxy Execution', 'defense-evasion'),
    '1218.001': ('Compiled HTML File', 'defense-evasion'),
    '1218.002': ('Control Panel', 'defense-evasion'),
    '1218.003': ('CMSTP', 'defense-evasion'),
    '1218.004': ('InstallUtil', 'defense-evasion'),
    '1218.005': ('Mshta', 'defense-evasion'),
    '1218.007': ('Msiexec', 'defense-evasion'),
    '1218.008': ('Odbcconf', 'defense-evasion'),
    '1218.009': ('Regsvcs/Regasm', 'defense-evasion'),
    '1218.010': ('Regsvr32', 'defense-evasion'),
    '1218.011': ('Rundll32', 'defense-evasion'),
    '1218.012': ('Verclsid', 'defense-evasion'),
    '1218.013': ('Mavinject', 'defense-evasion'),
    '1218.014': ('MMC', 'defense-evasion'),
    '1218.015': ('Electron Applications', 'defense-evasion'),
    '1219': ('Remote Access Tools', 'command-and-control'),
    '1219.001': ('IDE Tunneling', 'command-and-control'),
    '1219.002': ('Remote Desktop Software', 'command-and-control'),
    '1219.003': ('Remote Access Hardware', 'command-and-control'),
    '1220': ('XSL Script Processing', 'defense-evasion'),
    '1221': ('Template Injection', 'defense-evasion'),
    '1222': ('File and Directory Permissions Modification', 'defense-evasion'),
    '1222.001': ('Windows Permissions', 'defense-evasion'),
    '1222.002': ('Linux and Mac Permissions', 'defense-evasion'),
    '1480': ('Execution Guardrails', 'defense-evasion'),
    '1480.001': ('Environmental Keying', 'defense-evasion'),
    '1480.002': ('Mutual Exclusion', 'defense-evasion'),
    '1482': ('Domain Trust Discovery', 'discovery'),
    '1484': ('Domain or Tenant Policy Modification', 'privilege-escalation'),
    '1484b': ('Domain or Tenant Policy Modification', 'defense-evasion'),
    '1484.001': ('Group Policy Modification', 'privilege-escalation'),
    '1484.001b': ('Group Policy Modification', 'defense-evasion'),
    '1484.002': ('Trust Modification', 'privilege-escalation'),
    '1484.002b': ('Trust Modification', 'defense-evasion'),
    '1485': ('Data Destruction', 'impact'),
    '1485.001': ('Lifecycle-Triggered Deletion', 'impact'),
    '1486': ('Data Encrypted for Impact', 'impact'),
    '1489': ('Service Stop', 'impact'),
    '1490': ('Inhibit System Recovery', 'impact'),
    '1491': ('Defacement', 'impact'),
    '1491.001': ('Internal Defacement', 'impact'),
    '1491.002': ('External Defacement', 'impact'),
    '1495': ('Firmware Corruption', 'impact'),
    '1496': ('Resource Hijacking', 'impact'),
    '1496.001': ('Compute Hijacking', 'impact'),
    '1496.002': ('Bandwidth Hijacking', 'impact'),
    '1496.003': ('SMS Pumping', 'impact'),
    '1496.004': ('Cloud Service Hijacking', 'impact'),
    '1497': ('Virtualization/Sandbox Evasion', 'defense-evasion'),
    '1497b': ('Virtualization/Sandbox Evasion', 'discovery'),
    '1497.001': ('System Checks', 'defense-evasion'),
    '1497.001b': ('System Checks', 'discovery'),
    '1497.002': ('User Activity Based Checks', 'defense-evasion'),
    '1497.002b': ('User Activity Based Checks', 'discovery'),
    '1497.003': ('Time Based Checks', 'defense-evasion'),
    '1497.003b': ('Time Based Checks', 'discovery'),
    '1498': ('Network Denial of Service', 'impact'),
    '1498.001': ('Direct Network Flood', 'impact'),
    '1498.002': ('Reflection Amplification', 'impact'),
    '1499': ('Endpoint Denial of Service', 'impact'),
    '1499.001': ('OS Exhaustion Flood', 'impact'),
    '1499.002': ('Service Exhaustion Flood', 'impact'),
    '1499.003': ('Application Exhaustion Flood', 'impact'),
    '1499.004': ('Application or System Exploitation', 'impact'),
    '1505': ('Server Software Component', 'persistence'),
    '1505.001': ('SQL Stored Procedures', 'persistence'),
    '1505.002': ('Transport Agent', 'persistence'),
    '1505.003': ('Web Shell', 'persistence'),
    '1505.004': ('IIS Components', 'persistence'),
    '1505.005': ('Terminal Services DLL', 'persistence'),
    '1505.006': ('vSphere Installation Bundles', 'persistence'),
    '1518': ('Software Discovery', 'discovery'),
    '1518.001': ('Security Software Discovery', 'discovery'),
    '1518.002': ('Backup Software Discovery', 'discovery'),
    '1525': ('Implant Internal Image', 'persistence'),
    '1526': ('Cloud Service Discovery', 'discovery'),
    '1528': ('Steal Application Access Token', 'credential-access'),
    '1529': ('System Shutdown/Reboot', 'impact'),
    '1530': ('Data from Cloud Storage', 'collection'),
    '1531': ('Account Access Removal', 'impact'),
    '1534': ('Internal Spearphishing', 'lateral-movement'),
    '1535': ('Unused/Unsupported Cloud Regions', 'defense-evasion'),
    '1537': ('Transfer Data to Cloud Account', 'exfiltration'),
    '1538': ('Cloud Service Dashboard', 'discovery'),
    '1539': ('Steal Web Session Cookie', 'credential-access'),
    '1542': ('Pre-OS Boot', 'persistence'),
    '1542b': ('Pre-OS Boot', 'defense-evasion'),
    '1542.001': ('System Firmware', 'persistence'),
    '1542.001b': ('System Firmware', 'defense-evasion'),
    '1542.002': ('Component Firmware', 'persistence'),
    '1542.002b': ('Component Firmware', 'defense-evasion'),
    '1542.003': ('Bootkit', 'persistence'),
    '1542.003b': ('Bootkit', 'defense-evasion'),
    '1542.004': ('ROMMONkit', 'persistence'),
    '1542.004b': ('ROMMONkit', 'defense-evasion'),
    '1542.005': ('TFTP Boot', 'persistence'),
    '1542.005b': ('TFTP Boot', 'defense-evasion'),
    '1543': ('Create or Modify System Process', 'persistence'),
    '1543b': ('Create or Modify System Process', 'privilege-escalation'),
    '1543.001': ('Launch Agent', 'persistence'),
    '1543.001b': ('Launch Agent', 'privilege-escalation'),
    '1543.002': ('Systemd Service', 'persistence'),
    '1543.002b': ('Systemd Service', 'privilege-escalation'),
    '1543.003': ('Windows Service', 'persistence'),
    '1543.003b': ('Windows Service', 'privilege-escalation'),
    '1543.004': ('Launch Daemon', 'persistence'),
    '1543.004b': ('Launch Daemon', 'privilege-escalation'),
    '1543.005': ('Container Service', 'persistence'),
    '1543.005b': ('Container Service', 'privilege-escalation'),
    '1546': ('Event Triggered Execution', 'persistence'),
    '1546b': ('Event Triggered Execution', 'privilege-escalation'),
    '1546.001': ('Change Default File Association', 'persistence'),
    '1546.001b': ('Change Default File Association', 'privilege-escalation'),
    '1546.002': ('Screensaver', 'persistence'),
    '1546.002b': ('Screensaver', 'privilege-escalation'),
    '1546.003': ('Windows Management Instrumentation Event Subscription', 'persistence'),
    '1546.003b': ('Windows Management Instrumentation Event Subscription', 'privilege-escalation'),
    '1546.004': ('Unix Shell Configuration Modification', 'persistence'),
    '1546.004b': ('Unix Shell Configuration Modification', 'privilege-escalation'),
    '1546.005': ('Trap', 'persistence'),
    '1546.005b': ('Trap', 'privilege-escalation'),
    '1546.006': ('LC_LOAD_DYLIB Addition', 'persistence'),
    '1546.006b': ('LC_LOAD_DYLIB Addition', 'privilege-escalation'),
    '1546.007': ('Netsh Helper DLL', 'persistence'),
    '1546.007b': ('Netsh Helper DLL', 'privilege-escalation'),
    '1546.008': ('Accessibility Features', 'persistence'),
    '1546.008b': ('Accessibility Features', 'privilege-escalation'),
    '1546.009': ('AppCert DLLs', 'persistence'),
    '1546.009b': ('AppCert DLLs', 'privilege-escalation'),
    '1546.010': ('AppInit DLLs', 'persistence'),
    '1546.010b': ('AppInit DLLs', 'privilege-escalation'),
    '1546.011': ('Application Shimming', 'persistence'),
    '1546.011b': ('Application Shimming', 'privilege-escalation'),
    '1546.012': ('Image File Execution Options Injection', 'persistence'),
    '1546.012b': ('Image File Execution Options Injection', 'privilege-escalation'),
    '1546.013': ('PowerShell Profile', 'persistence'),
    '1546.013b': ('PowerShell Profile', 'privilege-escalation'),
    '1546.014': ('Emond', 'persistence'),
    '1546.014b': ('Emond', 'privilege-escalation'),
    '1546.015': ('Component Object Model Hijacking', 'persistence'),
    '1546.015b': ('Component Object Model Hijacking', 'privilege-escalation'),
    '1546.016': ('Installer Packages', 'persistence'),
    '1546.016b': ('Installer Packages', 'privilege-escalation'),
    '1546.017': ('Udev Rules', 'persistence'),
    '1546.017b': ('Udev Rules', 'privilege-escalation'),
    '1546.018': ('Python Startup Hooks', 'persistence'),
    '1546.018b': ('Python Startup Hooks', 'privilege-escalation'),
    '1547': ('Boot or Logon Autostart Execution', 'persistence'),
    '1547b': ('Boot or Logon Autostart Execution', 'privilege-escalation'),
    '1547.001': ('Registry Run Keys / Startup Folder', 'persistence'),
    '1547.001b': ('Registry Run Keys / Startup Folder', 'privilege-escalation'),
    '1547.002': ('Authentication Package', 'persistence'),
    '1547.002b': ('Authentication Package', 'privilege-escalation'),
    '1547.003': ('Time Providers', 'persistence'),
    '1547.003b': ('Time Providers', 'privilege-escalation'),
    '1547.004': ('Winlogon Helper DLL', 'persistence'),
    '1547.004b': ('Winlogon Helper DLL', 'privilege-escalation'),
    '1547.005': ('Security Support Provider', 'persistence'),
    '1547.005b': ('Security Support Provider', 'privilege-escalation'),
    '1547.006': ('Kernel Modules and Extensions', 'persistence'),
    '1547.006b': ('Kernel Modules and Extensions', 'privilege-escalation'),
    '1547.007': ('Re-opened Applications', 'persistence'),
    '1547.007b': ('Re-opened Applications', 'privilege-escalation'),
    '1547.008': ('LSASS Driver', 'persistence'),
    '1547.008b': ('LSASS Driver', 'privilege-escalation'),
    '1547.009': ('Shortcut Modification', 'persistence'),
    '1547.009b': ('Shortcut Modification', 'privilege-escalation'),
    '1547.010': ('Port Monitors', 'persistence'),
    '1547.010b': ('Port Monitors', 'privilege-escalation'),
    '1547.012': ('Print Processors', 'persistence'),
    '1547.012b': ('Print Processors', 'privilege-escalation'),
    '1547.013': ('XDG Autostart Entries', 'persistence'),
    '1547.013b': ('XDG Autostart Entries', 'privilege-escalation'),
    '1547.014': ('Active Setup', 'persistence'),
    '1547.014b': ('Active Setup', 'privilege-escalation'),
    '1547.015': ('Login Items', 'persistence'),
    '1547.015b': ('Login Items', 'privilege-escalation'),
    '1548': ('Abuse Elevation Control Mechanism', 'privilege-escalation'),
    '1548.001': ('Setuid and Setgid', 'privilege-escalation'),
    '1548.002': ('Bypass User Account Control', 'privilege-escalation'),
    '1548.003': ('Sudo and Sudo Caching', 'privilege-escalation'),
    '1548.004': ('Elevated Execution with Prompt', 'privilege-escalation'),
    '1548.005': ('Temporary Elevated Cloud Access', 'privilege-escalation'),
    '1548.006': ('TCC Manipulation', 'privilege-escalation'),
    '1550': ('Use Alternate Authentication Material', 'lateral-movement'),
    '1550.001': ('Application Access Token', 'lateral-movement'),
    '1550.002': ('Pass the Hash', 'lateral-movement'),
    '1550.003': ('Pass the Ticket', 'lateral-movement'),
    '1550.004': ('Web Session Cookie', 'lateral-movement'),
    '1552': ('Unsecured Credentials', 'credential-access'),
    '1552.001': ('Credentials In Files', 'credential-access'),
    '1552.002': ('Credentials in Registry', 'credential-access'),
    '1552.003': ('Shell History', 'credential-access'),
    '1552.004': ('Private Keys', 'credential-access'),
    '1552.005': ('Cloud Instance Metadata API', 'credential-access'),
    '1552.006': ('Group Policy Preferences', 'credential-access'),
    '1552.007': ('Container API', 'credential-access'),
    '1552.008': ('Chat Messages', 'credential-access'),
    '1553': ('Subvert Trust Controls', 'defense-evasion'),
    '1553.001': ('Gatekeeper Bypass', 'defense-evasion'),
    '1553.002': ('Code Signing', 'defense-evasion'),
    '1553.003': ('SIP and Trust Provider Hijacking', 'defense-evasion'),
    '1553.004': ('Install Root Certificate', 'defense-evasion'),
    '1553.005': ('Mark-of-the-Web Bypass', 'defense-evasion'),
    '1553.006': ('Code Signing Policy Modification', 'defense-evasion'),
    '1554': ('Compromise Host Software Binary', 'persistence'),
    '1555': ('Credentials from Password Stores', 'credential-access'),
    '1555.001': ('Keychain', 'credential-access'),
    '1555.002': ('Securityd Memory', 'credential-access'),
    '1555.003': ('Credentials from Web Browsers', 'credential-access'),
    '1555.004': ('Windows Credential Manager', 'credential-access'),
    '1555.005': ('Password Managers', 'credential-access'),
    '1555.006': ('Cloud Secrets Management Stores', 'credential-access'),
    '1556': ('Modify Authentication Process', 'persistence'),
    '1556b': ('Modify Authentication Process', 'defense-evasion'),
    '1556c': ('Modify Authentication Process', 'credential-access'),
    '1556.001': ('Domain Controller Authentication', 'persistence'),
    '1556.001b': ('Domain Controller Authentication', 'defense-evasion'),
    '1556.001c': ('Domain Controller Authentication', 'credential-access'),
    '1556.002': ('Password Filter DLL', 'persistence'),
    '1556.002b': ('Password Filter DLL', 'defense-evasion'),
    '1556.002c': ('Password Filter DLL', 'credential-access'),
    '1556.003': ('Pluggable Authentication Modules', 'persistence'),
    '1556.003b': ('Pluggable Authentication Modules', 'defense-evasion'),
    '1556.003c': ('Pluggable Authentication Modules', 'credential-access'),
    '1556.004': ('Network Device Authentication', 'persistence'),
    '1556.004b': ('Network Device Authentication', 'defense-evasion'),
    '1556.004c': ('Network Device Authentication', 'credential-access'),
    '1556.005': ('Reversible Encryption', 'persistence'),
    '1556.005b': ('Reversible Encryption', 'defense-evasion'),
    '1556.005c': ('Reversible Encryption', 'credential-access'),
    '1556.006': ('Multi-Factor Authentication', 'persistence'),
    '1556.006b': ('Multi-Factor Authentication', 'defense-evasion'),
    '1556.006c': ('Multi-Factor Authentication', 'credential-access'),
    '1556.007': ('Hybrid Identity', 'persistence'),
    '1556.007b': ('Hybrid Identity', 'defense-evasion'),
    '1556.007c': ('Hybrid Identity', 'credential-access'),
    '1556.008': ('Network Provider DLL', 'persistence'),
    '1556.008b': ('Network Provider DLL', 'defense-evasion'),
    '1556.008c': ('Network Provider DLL', 'credential-access'),
    '1556.009': ('Conditional Access Policies', 'persistence'),
    '1556.009b': ('Conditional Access Policies', 'defense-evasion'),
    '1556.009c': ('Conditional Access Policies', 'credential-access'),
    '1557': ('Adversary-in-the-Middle', 'credential-access'),
    '1557b': ('Adversary-in-the-Middle', 'collection'),
    '1557.001': ('Name Resolution Poisoning and SMB Relay', 'credential-access'),
    '1557.001b': ('Name Resolution Poisoning and SMB Relay', 'collection'),
    '1557.002': ('ARP Cache Poisoning', 'credential-access'),
    '1557.002b': ('ARP Cache Poisoning', 'collection'),
    '1557.003': ('DHCP Spoofing', 'credential-access'),
    '1557.003b': ('DHCP Spoofing', 'collection'),
    '1557.004': ('Evil Twin', 'credential-access'),
    '1557.004b': ('Evil Twin', 'collection'),
    '1558': ('Steal or Forge Kerberos Tickets', 'credential-access'),
    '1558.001': ('Golden Ticket', 'credential-access'),
    '1558.002': ('Silver Ticket', 'credential-access'),
    '1558.003': ('Kerberoasting', 'credential-access'),
    '1558.004': ('AS-REP Roasting', 'credential-access'),
    '1558.005': ('Ccache Files', 'credential-access'),
    '1559': ('Inter-Process Communication', 'execution'),
    '1559.001': ('Component Object Model', 'execution'),
    '1559.002': ('Dynamic Data Exchange', 'execution'),
    '1559.003': ('XPC Services', 'execution'),
    '1560': ('Archive Collected Data', 'collection'),
    '1560.001': ('Archive via Utility', 'collection'),
    '1560.002': ('Archive via Library', 'collection'),
    '1560.003': ('Archive via Custom Method', 'collection'),
    '1561': ('Disk Wipe', 'impact'),
    '1561.001': ('Disk Content Wipe', 'impact'),
    '1561.002': ('Disk Structure Wipe', 'impact'),
    '1563': ('Remote Service Session Hijacking', 'lateral-movement'),
    '1563.001': ('SSH Hijacking', 'lateral-movement'),
    '1563.002': ('RDP Hijacking', 'lateral-movement'),
    '1564': ('Hide Artifacts', 'defense-evasion'),
    '1564.001': ('Hidden Files and Directories', 'defense-evasion'),
    '1564.002': ('Hidden Users', 'defense-evasion'),
    '1564.003': ('Hidden Window', 'defense-evasion'),
    '1564.004': ('NTFS File Attributes', 'defense-evasion'),
    '1564.005': ('Hidden File System', 'defense-evasion'),
    '1564.006': ('Run Virtual Instance', 'defense-evasion'),
    '1564.007': ('VBA Stomping', 'defense-evasion'),
    '1564.008': ('Email Hiding Rules', 'defense-evasion'),
    '1564.009': ('Resource Forking', 'defense-evasion'),
    '1564.010': ('Process Argument Spoofing', 'defense-evasion'),
    '1564.011': ('Ignore Process Interrupts', 'defense-evasion'),
    '1564.012': ('File/Path Exclusions', 'defense-evasion'),
    '1564.013': ('Bind Mounts', 'defense-evasion'),
    '1564.014': ('Extended Attributes', 'defense-evasion'),
    '1565': ('Data Manipulation', 'impact'),
    '1565.001': ('Stored Data Manipulation', 'impact'),
    '1565.002': ('Transmitted Data Manipulation', 'impact'),
    '1565.003': ('Runtime Data Manipulation', 'impact'),
    '1566': ('Phishing', 'initial-access'),
    '1566.001': ('Spearphishing Attachment', 'initial-access'),
    '1566.002': ('Spearphishing Link', 'initial-access'),
    '1566.003': ('Spearphishing via Service', 'initial-access'),
    '1566.004': ('Spearphishing Voice', 'initial-access'),
    '1567': ('Exfiltration Over Web Service', 'exfiltration'),
    '1567.001': ('Exfiltration to Code Repository', 'exfiltration'),
    '1567.002': ('Exfiltration to Cloud Storage', 'exfiltration'),
    '1567.003': ('Exfiltration to Text Storage Sites', 'exfiltration'),
    '1567.004': ('Exfiltration Over Webhook', 'exfiltration'),
    '1568': ('Dynamic Resolution', 'command-and-control'),
    '1568.001': ('Fast Flux DNS', 'command-and-control'),
    '1568.002': ('Domain Generation Algorithms', 'command-and-control'),
    '1568.003': ('DNS Calculation', 'command-and-control'),
    '1569': ('System Services', 'execution'),
    '1569.001': ('Launchctl', 'execution'),
    '1569.002': ('Service Execution', 'execution'),
    '1569.003': ('Systemctl', 'execution'),
    '1570': ('Lateral Tool Transfer', 'lateral-movement'),
    '1571': ('Non-Standard Port', 'command-and-control'),
    '1572': ('Protocol Tunneling', 'command-and-control'),
    '1573': ('Encrypted Channel', 'command-and-control'),
    '1573.001': ('Symmetric Cryptography', 'command-and-control'),
    '1573.002': ('Asymmetric Cryptography', 'command-and-control'),
    '1574': ('Hijack Execution Flow', 'execution'),
    '1574b': ('Hijack Execution Flow', 'defense-evasion'),
    '1574.001': ('DLL', 'execution'),
    '1574.001b': ('DLL', 'defense-evasion'),
    '1574.004': ('Dylib Hijacking', 'execution'),
    '1574.004b': ('Dylib Hijacking', 'defense-evasion'),
    '1574.005': ('Executable Installer File Permissions Weakness', 'execution'),
    '1574.005b': ('Executable Installer File Permissions Weakness', 'defense-evasion'),
    '1574.006': ('Dynamic Linker Hijacking', 'execution'),
    '1574.006b': ('Dynamic Linker Hijacking', 'defense-evasion'),
    '1574.007': ('Path Interception by PATH Environment Variable', 'execution'),
    '1574.007b': ('Path Interception by PATH Environment Variable', 'defense-evasion'),
    '1574.008': ('Path Interception by Search Order Hijacking', 'execution'),
    '1574.008b': ('Path Interception by Search Order Hijacking', 'defense-evasion'),
    '1574.009': ('Path Interception by Unquoted Path', 'execution'),
    '1574.009b': ('Path Interception by Unquoted Path', 'defense-evasion'),
    '1574.010': ('Services File Permissions Weakness', 'execution'),
    '1574.010b': ('Services File Permissions Weakness', 'defense-evasion'),
    '1574.011': ('Services Registry Permissions Weakness', 'execution'),
    '1574.011b': ('Services Registry Permissions Weakness', 'defense-evasion'),
    '1574.012': ('COR_PROFILER', 'execution'),
    '1574.012b': ('COR_PROFILER', 'defense-evasion'),
    '1574.013': ('KernelCallbackTable', 'execution'),
    '1574.013b': ('KernelCallbackTable', 'defense-evasion'),
    '1574.014': ('AppDomainManager', 'execution'),
    '1574.014b': ('AppDomainManager', 'defense-evasion'),
    '1578': ('Modify Cloud Compute Infrastructure', 'defense-evasion'),
    '1578.001': ('Create Snapshot', 'defense-evasion'),
    '1578.002': ('Create Cloud Instance', 'defense-evasion'),
    '1578.003': ('Delete Cloud Instance', 'defense-evasion'),
    '1578.004': ('Revert Cloud Instance', 'defense-evasion'),
    '1578.005': ('Modify Cloud Compute Configurations', 'defense-evasion'),
    '1580': ('Cloud Infrastructure Discovery', 'discovery'),
    '1583': ('Acquire Infrastructure', 'resource-development'),
    '1583.001': ('Domains', 'resource-development'),
    '1583.002': ('DNS Server', 'resource-development'),
    '1583.003': ('Virtual Private Server', 'resource-development'),
    '1583.004': ('Server', 'resource-development'),
    '1583.005': ('Botnet', 'resource-development'),
    '1583.006': ('Web Services', 'resource-development'),
    '1583.007': ('Serverless', 'resource-development'),
    '1583.008': ('Malvertising', 'resource-development'),
    '1584': ('Compromise Infrastructure', 'resource-development'),
    '1584.001': ('Domains', 'resource-development'),
    '1584.002': ('DNS Server', 'resource-development'),
    '1584.003': ('Virtual Private Server', 'resource-development'),
    '1584.004': ('Server', 'resource-development'),
    '1584.005': ('Botnet', 'resource-development'),
    '1584.006': ('Web Services', 'resource-development'),
    '1584.007': ('Serverless', 'resource-development'),
    '1584.008': ('Network Devices', 'resource-development'),
    '1585': ('Establish Accounts', 'resource-development'),
    '1585.001': ('Social Media Accounts', 'resource-development'),
    '1585.002': ('Email Accounts', 'resource-development'),
    '1585.003': ('Cloud Accounts', 'resource-development'),
    '1586': ('Compromise Accounts', 'resource-development'),
    '1586.001': ('Social Media Accounts', 'resource-development'),
    '1586.002': ('Email Accounts', 'resource-development'),
    '1586.003': ('Cloud Accounts', 'resource-development'),
    '1587': ('Develop Capabilities', 'resource-development'),
    '1587.001': ('Malware', 'resource-development'),
    '1587.002': ('Code Signing Certificates', 'resource-development'),
    '1587.003': ('Digital Certificates', 'resource-development'),
    '1587.004': ('Exploits', 'resource-development'),
    '1588': ('Obtain Capabilities', 'resource-development'),
    '1588.001': ('Malware', 'resource-development'),
    '1588.002': ('Tool', 'resource-development'),
    '1588.003': ('Code Signing Certificates', 'resource-development'),
    '1588.004': ('Digital Certificates', 'resource-development'),
    '1588.005': ('Exploits', 'resource-development'),
    '1588.006': ('Vulnerabilities', 'resource-development'),
    '1588.007': ('Artificial Intelligence', 'resource-development'),
    '1589': ('Gather Victim Identity Information', 'reconnaissance'),
    '1589.001': ('Credentials', 'reconnaissance'),
    '1589.002': ('Email Addresses', 'reconnaissance'),
    '1589.003': ('Employee Names', 'reconnaissance'),
    '1590': ('Gather Victim Network Information', 'reconnaissance'),
    '1590.001': ('Domain Properties', 'reconnaissance'),
    '1590.002': ('DNS', 'reconnaissance'),
    '1590.003': ('Network Trust Dependencies', 'reconnaissance'),
    '1590.004': ('Network Topology', 'reconnaissance'),
    '1590.005': ('IP Addresses', 'reconnaissance'),
    '1590.006': ('Network Security Appliances', 'reconnaissance'),
    '1591': ('Gather Victim Org Information', 'reconnaissance'),
    '1591.001': ('Determine Physical Locations', 'reconnaissance'),
    '1591.002': ('Business Relationships', 'reconnaissance'),
    '1591.003': ('Identify Business Tempo', 'reconnaissance'),
    '1591.004': ('Identify Roles', 'reconnaissance'),
    '1592': ('Gather Victim Host Information', 'reconnaissance'),
    '1592.001': ('Hardware', 'reconnaissance'),
    '1592.002': ('Software', 'reconnaissance'),
    '1592.003': ('Firmware', 'reconnaissance'),
    '1592.004': ('Client Configurations', 'reconnaissance'),
    '1593': ('Search Open Websites/Domains', 'reconnaissance'),
    '1593.001': ('Social Media', 'reconnaissance'),
    '1593.002': ('Search Engines', 'reconnaissance'),
    '1593.003': ('Code Repositories', 'reconnaissance'),
    '1594': ('Search Victim-Owned Websites', 'reconnaissance'),
    '1595': ('Active Scanning', 'reconnaissance'),
    '1595.001': ('Scanning IP Blocks', 'reconnaissance'),
    '1595.002': ('Vulnerability Scanning', 'reconnaissance'),
    '1595.003': ('Wordlist Scanning', 'reconnaissance'),
    '1596': ('Search Open Technical Databases', 'reconnaissance'),
    '1596.001': ('DNS/Passive DNS', 'reconnaissance'),
    '1596.002': ('WHOIS', 'reconnaissance'),
    '1596.003': ('Digital Certificates', 'reconnaissance'),
    '1596.004': ('CDNs', 'reconnaissance'),
    '1596.005': ('Scan Databases', 'reconnaissance'),
    '1597': ('Search Closed Sources', 'reconnaissance'),
    '1597.001': ('Threat Intel Vendors', 'reconnaissance'),
    '1597.002': ('Purchase Technical Data', 'reconnaissance'),
    '1598': ('Phishing for Information', 'reconnaissance'),
    '1598.001': ('Spearphishing Service', 'reconnaissance'),
    '1598.002': ('Spearphishing Attachment', 'reconnaissance'),
    '1598.003': ('Spearphishing Link', 'reconnaissance'),
    '1598.004': ('Spearphishing Voice', 'reconnaissance'),
    '1599': ('Network Boundary Bridging', 'defense-evasion'),
    '1599.001': ('Network Address Translation Traversal', 'defense-evasion'),
    '1600': ('Weaken Encryption', 'defense-evasion'),
    '1600.001': ('Reduce Key Space', 'defense-evasion'),
    '1600.002': ('Disable Crypto Hardware', 'defense-evasion'),
    '1601': ('Modify System Image', 'defense-evasion'),
    '1601.001': ('Patch System Image', 'defense-evasion'),
    '1601.002': ('Downgrade System Image', 'defense-evasion'),
    '1602': ('Data from Configuration Repository', 'collection'),
    '1602.001': ('SNMP (MIB Dump)', 'collection'),
    '1602.002': ('Network Device Configuration Dump', 'collection'),
    '1606': ('Forge Web Credentials', 'credential-access'),
    '1606.001': ('Web Cookies', 'credential-access'),
    '1606.002': ('SAML Tokens', 'credential-access'),
    '1608': ('Stage Capabilities', 'resource-development'),
    '1608.001': ('Upload Malware', 'resource-development'),
    '1608.002': ('Upload Tool', 'resource-development'),
    '1608.003': ('Install Digital Certificate', 'resource-development'),
    '1608.004': ('Drive-by Target', 'resource-development'),
    '1608.005': ('Link Target', 'resource-development'),
    '1608.006': ('SEO Poisoning', 'resource-development'),
    '1609': ('Container Administration Command', 'execution'),
    '1610': ('Deploy Container', 'execution'),
    '1611': ('Escape to Host', 'privilege-escalation'),
    '1612': ('Build Image on Host', 'defense-evasion'),
    '1613': ('Container and Resource Discovery', 'discovery'),
    '1614': ('System Location Discovery', 'discovery'),
    '1614.001': ('System Language Discovery', 'discovery'),
    '1615': ('Group Policy Discovery', 'discovery'),
    '1619': ('Cloud Storage Object Discovery', 'discovery'),
    '1620': ('Reflective Code Loading', 'defense-evasion'),
    '1621': ('Multi-Factor Authentication Request Generation', 'credential-access'),
    '1622': ('Debugger Evasion', 'defense-evasion'),
    '1622b': ('Debugger Evasion', 'discovery'),
    '1647': ('Plist File Modification', 'defense-evasion'),
    '1648': ('Serverless Execution', 'execution'),
    '1649': ('Steal or Forge Authentication Certificates', 'credential-access'),
    '1650': ('Acquire Access', 'resource-development'),
    '1651': ('Cloud Administration Command', 'execution'),
    '1652': ('Device Driver Discovery', 'discovery'),
    '1653': ('Power Settings', 'persistence'),
    '1654': ('Log Enumeration', 'discovery'),
    '1657': ('Financial Theft', 'impact'),
    '1659': ('Content Injection', 'initial-access'),
    '1659b': ('Content Injection', 'command-and-control'),
    '1665': ('Hide Infrastructure', 'command-and-control'),
    '1666': ('Modify Cloud Resource Hierarchy', 'defense-evasion'),
    '1667': ('Email Bombing', 'impact'),
    '1668': ('Exclusive Control', 'persistence'),
    '1669': ('Wi-Fi Networks', 'initial-access'),
    '1671': ('Cloud Application Integration', 'persistence'),
    '1673': ('Virtual Machine Discovery', 'discovery'),
    '1674': ('Input Injection', 'execution'),
    '1675': ('ESXi Administration Command', 'execution'),
    '1677': ('Poisoned Pipeline Execution', 'execution'),
    '1678': ('Delay Execution', 'defense-evasion'),
    '1679': ('Selective Exclusion', 'defense-evasion'),
    '1680': ('Local Storage Discovery', 'discovery'),
    '1681': ('Search Threat Vendor Data', 'reconnaissance'),
    '1682': ('Query Public AI Services', 'reconnaissance'),
    '1683': ('Generate Content', 'resource-development'),
    '1683.001': ('Written Content', 'resource-development'),
    '1683.002': ('Audio-Visual Content', 'resource-development'),
    '1684': ('Social Engineering', 'defense-evasion'),
    '1684.001': ('Impersonation', 'defense-evasion'),
    '1684.002': ('Email Spoofing', 'defense-evasion'),
    '1685': ('Disable or Modify Tools', 'defense-evasion'),
    '1685.001': ('Disable or Modify Windows Event Log', 'defense-evasion'),
    '1685.002': ('Disable or Modify Cloud Log', 'defense-evasion'),
    '1685.003': ('Modify or Spoof Tool UI', 'defense-evasion'),
    '1685.004': ('Disable or Modify Linux Audit System Log', 'defense-evasion'),
    '1685.005': ('Clear Windows Event Logs', 'defense-evasion'),
    '1685.006': ('Clear Linux or Mac System Logs', 'defense-evasion'),
    '1686': ('Disable or Modify System Firewall', 'defense-evasion'),
    '1686.001': ('Cloud Firewall', 'defense-evasion'),
    '1686.002': ('Network Device Firewall', 'defense-evasion'),
    '1686.003': ('Windows Host Firewall', 'defense-evasion'),
    '1687': ('Exploitation for Defense Impairment', 'defense-evasion'),
    '1688': ('Safe Mode Boot', 'defense-evasion'),
    '1689': ('Downgrade Attack', 'defense-evasion'),
    '1690': ('Prevent Command History Logging', 'defense-evasion'),
}

def _display_id(key):
    return re.sub(r'[a-z]+$', '', key)

_TECH_TAG_RE = re.compile(r'^attack\.t(\d{4})(?:\.(\d{3}))?$', re.IGNORECASE)

# lookup() used to be a linear scan over TECHNIQUES.items() (872 entries) with a
# _display_id() regex substitution per candidate -- called once per technique tag on
# every Sigma rule (techniques_for_tags()), so this ran thousands of times per
# /api/mitre/coverage request (~4050 rules in production) and was measured as the
# dominant cost of that endpoint's 13-15s latency. Precomputed once at import time
# instead: setdefault() preserves the original scan's "first entry in TECHNIQUES'
# definition order wins" semantics for ids that appear more than once (e.g. T1078's
# '1078'/'1078b'/'1078c'/'1078d' tactic-variants all display as '1078') -- the linear
# scan always returned on the FIRST match it hit, so a later-defined entry must never
# silently override an earlier one here either.
_DISPLAY_ID_INDEX = {}
for _key, _entry in TECHNIQUES.items():
    _DISPLAY_ID_INDEX.setdefault(_display_id(_key), _entry)
del _key, _entry


def lookup(technique_id):
    """Look up a technique ID like '1059.001' or '1059'. Returns (name, tactic)
    or (None, 'unmapped') if not in the curated table. Falls back to the
    parent technique's tactic when only the sub-technique is unlisted."""
    entry = _DISPLAY_ID_INDEX.get(technique_id)
    if entry:
        return entry
    if '.' in technique_id:
        parent_entry = _DISPLAY_ID_INDEX.get(technique_id.split('.', 1)[0])
        if parent_entry:
            return None, parent_entry[1]
    return None, 'unmapped'


def techniques_for_tags(tags):
    """Extract MITRE technique IDs from a Sigma rule's parsed tag list.
    Returns a list of {id, name, tactic} dicts, one per distinct technique
    tag found (tactic-name-only tags like 'attack.execution' are ignored --
    those don't identify a specific technique to count)."""
    out = []
    seen = set()
    for tag in tags or []:
        m = _TECH_TAG_RE.match((tag or '').strip())
        if not m:
            continue
        tid = m.group(1) + (f'.{m.group(2)}' if m.group(2) else '')
        if tid in seen:
            continue
        seen.add(tid)
        name, tactic = lookup(tid)
        out.append({'id': tid, 'name': name, 'tactic': tactic})
    return out
